app_identifier "com.yuhsiangjiang.GuoYueZhiPu"
username ENV.fetch("FASTLANE_APPLE_ID", "jushiung@gmail.com")
team_id "7H7ZUG2WX8"

metadata_path "./metadata"
screenshots_path "./screenshots"

app_version "1.1"
copyright "Copyright © 2026 Yu Shiung Jiang"
primary_category "EDUCATION"
secondary_category "MUSIC"

automatic_release true
force true
overwrite_screenshots true
run_precheck_before_submit true
reject_if_possible false
submission_information({
  add_id_info_uses_idfa: false,
  export_compliance_uses_encryption: false,
  export_compliance_is_exempt: true,
  content_rights_contains_third_party_content: false,
  content_rights_has_rights: true
})
