#!/usr/bin/env python3
import argparse
import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PACK_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "priority1_recording_delivery_pack.json"
)
SCORECARD_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "professional_listening_review_scorecard.json"
)
DOC_PATH = ROOT / "Docs" / "AssetLicenses" / "Phase1RecordingInboxValidation.zh-Hant.md"

REQUIRED_IDS = ["erhu", "gaohu", "zhonghu", "gehu", "sheng", "suona", "banhu"]
REVERIFY_IDS = {"sheng"}
REQUIRED_CONFIRMATIONS = {
    "real_instrument_recording",
    "commercial_app_distribution",
    "derivative_processing_allowed",
    "global_perpetual_use",
    "not_ai_generated",
    "not_vst_or_sample_library",
    "not_ripped_from_streaming_or_video",
}
BANNED_RELEASE_SOURCE_PATTERNS = [
    (r"\bsuno\b", "Suno"),
    (r"\budio\b", "Udio"),
    (r"\bmusicgen\b", "MusicGen"),
    (r"\bstable audio\b", "Stable Audio"),
    (r"\bai-generated\b", "AI-generated"),
    (r"\bai generated\b", "AI generated"),
    (r"\bgenerated by ai\b", "generated by AI"),
    (r"\bgenerative music\b", "generative music"),
    (r"\bvst\b", "VST"),
    (r"\bsample library\b", "sample library"),
    (r"\bmidi\b", "MIDI"),
    (r"\bsynthesizer\b", "synthesizer"),
    (r"\bgarageband\b", "GarageBand"),
    (r"\byoutube\b", "YouTube"),
    (r"\bspotify\b", "Spotify"),
    (r"\bapple music\b", "Apple Music"),
    (r"\bcd rip\b", "CD rip"),
    (r"\bstreaming extraction\b", "streaming extraction"),
]
REQUIRED_DOC_TOKENS = [
    "priority1_recording_delivery_pack.json",
    "Design/Source/VerifiedAudio/inbox/full/<instrument_id>/",
    "Design/Source/VerifiedAudio/inbox/reverify/sheng/",
    "sheng",
    "approved_for_import",
    "import_recording_inbox_batch.py --pack priority1",
    "Suno",
    "AI-generated instrument tone",
    "VST",
    "sample library",
]


def load_json(path):
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def has_placeholder(value):
    if isinstance(value, str):
        return "TO_BE_FILLED" in value
    if isinstance(value, dict):
        return any(has_placeholder(child) for child in value.values())
    if isinstance(value, list):
        return any(has_placeholder(child) for child in value)
    return False


def searchable_release_text(release):
    searchable_keys = [
        "source_title",
        "source_type",
        "performer_or_source",
        "source_url",
        "original_source_url",
        "license",
        "license_review",
        "composition_rights_status",
        "notes",
    ]
    return " ".join(str(release.get(key, "")) for key in searchable_keys).lower()


def duration_seconds(path):
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return float(result.stdout.strip())


def validate_release(path, instrument_id, required_confirmations):
    failures = []
    release = load_json(path)

    if release.get("template_only") is True:
        failures.append(f"{instrument_id}: release must not have template_only=true")
    if release.get("instrument_id") != instrument_id:
        failures.append(f"{instrument_id}: release.instrument_id mismatch")
    if has_placeholder(release):
        failures.append(f"{instrument_id}: release still contains TO_BE_FILLED placeholder")

    for key in [
        "instrument_name_zh",
        "source_title",
        "source_type",
        "performer_or_source",
        "recording_date",
        "license",
        "license_url_or_document",
        "composition_rights_status",
    ]:
        if not str(release.get(key, "")).strip():
            failures.append(f"{instrument_id}: release.{key} is required")

    confirmations = release.get("confirmations") or {}
    for key in required_confirmations:
        if confirmations.get(key) is not True:
            failures.append(f"{instrument_id}: release.confirmations.{key} must be true")

    release_text = searchable_release_text(release)
    banned_hits = [
        label
        for pattern, label in BANNED_RELEASE_SOURCE_PATTERNS
        if re.search(pattern, release_text)
    ]
    if banned_hits:
        failures.append(
            f"{instrument_id}: release source text contains banned source token(s): "
            + ", ".join(sorted(set(banned_hits)))
        )

    return failures


def approved_review_ids(scorecard):
    return {
        record.get("instrument_id")
        for record in scorecard.get("review_records", [])
        if record.get("decision") == "approved_for_import"
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate priority-1 real-instrument recording inbox deliveries, including sheng reverify."
    )
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    failures = []
    warnings = []
    pack = load_json(PACK_PATH)
    scorecard = load_json(SCORECARD_PATH)
    doc_text = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""

    if pack.get("required_instrument_ids") != REQUIRED_IDS:
        failures.append("priority1 pack required_instrument_ids must preserve the phase-1 order")
    rules = pack.get("global_delivery_rules") or {}
    required_confirmations = set(rules.get("required_release_confirmations", []))
    if required_confirmations != REQUIRED_CONFIRMATIONS:
        failures.append("priority1 pack required_release_confirmations mismatch")
    if int(rules.get("minimum_takes_per_instrument", 0)) < 3:
        failures.append("priority1 pack minimum_takes_per_instrument must be at least 3")
    minimum_seconds = int(rules.get("minimum_clean_duration_seconds", 0))
    if minimum_seconds < 6:
        failures.append("priority1 pack minimum_clean_duration_seconds must be at least 6")

    if not DOC_PATH.exists():
        failures.append("Missing Phase1RecordingInboxValidation.zh-Hant.md")
    else:
        for token in REQUIRED_DOC_TOKENS:
            if token not in doc_text:
                failures.append(f"Phase1RecordingInboxValidation.zh-Hant.md missing token: {token}")

    approved_ids = approved_review_ids(scorecard)
    pack_by_id = {item.get("instrument_id"): item for item in pack.get("items", [])}
    if set(pack_by_id) != set(REQUIRED_IDS):
        failures.append("priority1 pack items must exactly match phase-1 instruments")

    delivered_count = 0
    complete_count = 0
    for instrument_id in REQUIRED_IDS:
        item = pack_by_id.get(instrument_id)
        if not item:
            continue

        expected_folder = (
            f"Design/Source/VerifiedAudio/inbox/reverify/{instrument_id}/"
            if instrument_id in REVERIFY_IDS
            else f"Design/Source/VerifiedAudio/inbox/full/{instrument_id}/"
        )
        if item.get("delivery_folder") != expected_folder:
            failures.append(f"{instrument_id}: delivery_folder must be {expected_folder}")

        folder = ROOT / item.get("delivery_folder", "")
        if not folder.exists():
            continue
        folder_files = [path for path in folder.iterdir() if path.is_file() and not path.name.startswith(".")]
        if not folder_files:
            continue
        delivered_count += 1

        expected_audio = {take.get("filename") for take in item.get("take_specs", [])}
        expected_release = f"{instrument_id}.release.json"
        actual_names = {path.name for path in folder_files}
        missing_audio = sorted(expected_audio - actual_names)
        if missing_audio:
            failures.append(f"{instrument_id}: missing expected take file(s): {', '.join(missing_audio)}")

        release_path = folder / expected_release
        if expected_release not in actual_names:
            failures.append(f"{instrument_id}: missing release file {expected_release}")
        else:
            failures.extend(validate_release(release_path, instrument_id, required_confirmations))

        accepted_extensions = {".wav", ".aiff", ".aif"}
        unexpected_audio = sorted(
            name
            for name in actual_names
            if Path(name).suffix.lower() in accepted_extensions and name not in expected_audio
        )
        if unexpected_audio:
            failures.append(f"{instrument_id}: unexpected audio file(s): {', '.join(unexpected_audio)}")

        for filename in sorted(expected_audio & actual_names):
            path = folder / filename
            suffix = path.suffix.lower()
            if suffix not in accepted_extensions:
                failures.append(f"{instrument_id}: unsupported audio extension: {filename}")
                continue
            try:
                seconds = duration_seconds(path)
            except Exception as exc:
                failures.append(f"{instrument_id}: cannot inspect duration for {filename}: {exc}")
                continue
            if seconds < minimum_seconds:
                failures.append(f"{instrument_id}: {filename} is too short: {seconds:.2f}s")

        has_all_audio = not missing_audio
        has_release = expected_release in actual_names
        if has_all_audio and has_release:
            complete_count += 1
            if instrument_id not in approved_ids:
                message = f"{instrument_id}: complete phase-1 delivery still needs professional review decision approved_for_import"
                if args.strict:
                    failures.append(message)
                else:
                    warnings.append(message)

    print(
        "Phase-1 recording inbox: "
        + f"{delivered_count} delivered folder(s), {complete_count} complete folder(s), "
        + f"{len(approved_ids)} approved review record(s)."
    )
    for warning in warnings:
        print(f"WARNING: {warning}")

    if failures:
        print("\nPhase-1 recording inbox check failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print("Phase-1 recording inbox check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
