#!/usr/bin/env python3
import argparse
import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INBOX_MANIFEST_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "recording_inbox_manifest.json"
)
PACK_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "full_open_recording_delivery_pack.json"
)
SCORECARD_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "professional_listening_review_scorecard.json"
)
WORK_ORDER_PATH = (
    ROOT
    / "Design"
    / "Source"
    / "VerifiedAudio"
    / "procurement"
    / "performer_recording_work_order.json"
)
DOC_PATH = ROOT / "Docs" / "AssetLicenses" / "RecordingInboxValidation.zh-Hant.md"

REQUIRED_DOC_TOKENS = [
    "Design/Source/VerifiedAudio/inbox/full/<instrument_id>/",
    "<instrument_id>.release.json",
    "approved_for_import",
    "import_verified_audio.py",
    "禁用來源掃描",
    "Suno",
    "Stable Audio",
    "sample library",
]

REQUIRED_CONFIRMATIONS = {
    "real_instrument_recording",
    "commercial_app_distribution",
    "derivative_processing_allowed",
    "global_perpetual_use",
    "not_ai_generated",
    "not_vst_or_sample_library",
    "not_ripped_from_streaming_or_video",
}

BANNED_RELEASE_SOURCE_PATTERNS = [
    (r"\bsuno\b", "Suno"),
    (r"\budio\b", "Udio"),
    (r"\bmusicgen\b", "MusicGen"),
    (r"\bstable audio\b", "Stable Audio"),
    (r"\bai-generated\b", "AI-generated"),
    (r"\bai generated\b", "AI generated"),
    (r"\bgenerated by ai\b", "generated by AI"),
    (r"\bgenerative music\b", "generative music"),
    (r"\bvst\b", "VST"),
    (r"\bsample library\b", "sample library"),
    (r"\bmidi\b", "MIDI"),
    (r"\bsynthesizer\b", "synthesizer"),
    (r"\bgarageband\b", "GarageBand"),
    (r"\byoutube\b", "YouTube"),
    (r"\bspotify\b", "Spotify"),
    (r"\bapple music\b", "Apple Music"),
    (r"\bcd rip\b", "CD rip"),
    (r"\bstreaming extraction\b", "streaming extraction"),
]

REQUIRED_BANNED_SOURCE_LABELS = {
    "Suno",
    "AI-generated",
    "VST",
    "sample library",
    "YouTube",
    "streaming extraction",
}


def load_json(path):
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def has_placeholder(value):
    if isinstance(value, str):
        return "TO_BE_FILLED" in value
    if isinstance(value, dict):
        return any(has_placeholder(child) for child in value.values())
    if isinstance(value, list):
        return any(has_placeholder(child) for child in value)
    return False


def searchable_release_text(release):
    searchable_keys = [
        "source_title",
        "source_type",
        "performer_or_source",
        "source_url",
        "original_source_url",
        "license",
        "license_review",
        "composition_rights_status",
        "notes",
    ]
    return " ".join(str(release.get(key, "")) for key in searchable_keys).lower()


def duration_seconds(path):
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return float(result.stdout.strip())


def validate_release(path, instrument_id, required_confirmations):
    failures = []
    release = load_json(path)

    if release.get("template_only") is True:
        failures.append(f"{instrument_id}: release must not have template_only=true")
    if release.get("instrument_id") != instrument_id:
        failures.append(f"{instrument_id}: release.instrument_id mismatch")
    if has_placeholder(release):
        failures.append(f"{instrument_id}: release still contains TO_BE_FILLED placeholder")

    for key in [
        "instrument_name_zh",
        "source_title",
        "source_type",
        "performer_or_source",
        "recording_date",
        "license",
        "license_url_or_document",
        "composition_rights_status",
    ]:
        if not str(release.get(key, "")).strip():
            failures.append(f"{instrument_id}: release.{key} is required")

    confirmations = release.get("confirmations") or {}
    for key in required_confirmations:
        if confirmations.get(key) is not True:
            failures.append(f"{instrument_id}: release.confirmations.{key} must be true")

    release_text = searchable_release_text(release)
    banned_hits = [
        label
        for pattern, label in BANNED_RELEASE_SOURCE_PATTERNS
        if re.search(pattern, release_text)
    ]
    if banned_hits:
        failures.append(
            f"{instrument_id}: release source text contains banned source token(s): "
            + ", ".join(sorted(set(banned_hits)))
        )

    return failures


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate delivered performer recording inbox folders before import."
    )
    parser.add_argument("--strict", action="store_true")
    args = parser.parse_args()

    failures = []
    warnings = []

    manifest = load_json(INBOX_MANIFEST_PATH)
    pack = load_json(PACK_PATH)
    scorecard = load_json(SCORECARD_PATH)
    work_order = load_json(WORK_ORDER_PATH)
    doc_text = DOC_PATH.read_text(encoding="utf-8") if DOC_PATH.exists() else ""

    inbox_root = ROOT / manifest.get("inbox_root", "")
    reverify_root = ROOT / manifest.get("reverify_root", "")
    accepted_extensions = set(manifest.get("accepted_audio_extensions", []))
    required_confirmations = set(manifest.get("required_release_confirmations", []))
    banned_source_labels = set(manifest.get("banned_release_source_labels", []))
    if not inbox_root.exists():
        failures.append(f"recording inbox root does not exist: {inbox_root.relative_to(ROOT)}")
    if manifest.get("phase_1_reverify_instrument_ids") and not reverify_root.exists():
        failures.append(f"recording reverify root does not exist: {reverify_root.relative_to(ROOT)}")
    if required_confirmations != REQUIRED_CONFIRMATIONS:
        failures.append("recording inbox manifest required_release_confirmations mismatch")
    if not REQUIRED_BANNED_SOURCE_LABELS <= banned_source_labels:
        missing = sorted(REQUIRED_BANNED_SOURCE_LABELS - banned_source_labels)
        failures.append("recording inbox manifest missing banned_release_source_labels: " + ", ".join(missing))
    if not accepted_extensions >= {".wav", ".aiff", ".aif"}:
        failures.append("recording inbox manifest must accept wav/aiff/aif")
    if int(manifest.get("minimum_expected_takes", 0)) < 3:
        failures.append("recording inbox manifest minimum_expected_takes must be at least 3")
    if int(manifest.get("minimum_clean_seconds_per_take", 0)) < 6:
        failures.append("recording inbox manifest minimum_clean_seconds_per_take must be at least 6")

    if not DOC_PATH.exists():
        failures.append("Missing RecordingInboxValidation.zh-Hant.md")
    else:
        for token in REQUIRED_DOC_TOKENS:
            if token not in doc_text:
                failures.append(f"RecordingInboxValidation.zh-Hant.md missing token: {token}")

    pack_items = {item["instrument_id"]: item for item in pack.get("items", [])}
    phase_1_ids = set(manifest.get("phase_1_watch_instrument_ids", []))
    expected_phase_1_ids = set(work_order.get("phase_1_required_instrument_ids", []))
    if phase_1_ids != expected_phase_1_ids:
        failures.append(
            "recording inbox phase_1_watch_instrument_ids must match the current work order"
        )

    review_by_id = {}
    for record in scorecard.get("review_records", []):
        instrument_id = record.get("instrument_id")
        if instrument_id:
            review_by_id.setdefault(instrument_id, []).append(record)

    delivered_count = 0
    complete_count = 0
    for instrument_id, item in sorted(pack_items.items()):
        folder = ROOT / item["delivery_folder"]
        if not folder.exists():
            continue

        folder_files = [path for path in folder.iterdir() if not path.name.startswith(".")]
        if not folder_files:
            continue
        delivered_count += 1

        expected_audio = {take["filename"] for take in item.get("take_specs", [])}
        expected_release = f"{instrument_id}.release.json"
        actual_names = {path.name for path in folder_files if path.is_file()}
        missing_audio = sorted(expected_audio - actual_names)
        if missing_audio:
            failures.append(f"{instrument_id}: missing expected take file(s): {', '.join(missing_audio)}")

        release_path = folder / expected_release
        if expected_release not in actual_names:
            failures.append(f"{instrument_id}: missing release file {expected_release}")
        else:
            failures.extend(validate_release(release_path, instrument_id, required_confirmations))

        unexpected_audio = sorted(
            name
            for name in actual_names
            if Path(name).suffix.lower() in accepted_extensions and name not in expected_audio
        )
        if unexpected_audio:
            failures.append(f"{instrument_id}: unexpected audio file(s): {', '.join(unexpected_audio)}")

        for filename in sorted(expected_audio & actual_names):
            path = folder / filename
            suffix = path.suffix.lower()
            if suffix not in accepted_extensions:
                failures.append(f"{instrument_id}: unsupported audio extension: {filename}")
                continue
            try:
                seconds = duration_seconds(path)
            except Exception as exc:
                failures.append(f"{instrument_id}: cannot inspect duration for {filename}: {exc}")
                continue
            if seconds < int(manifest.get("minimum_clean_seconds_per_take", 6)):
                failures.append(f"{instrument_id}: {filename} is too short: {seconds:.2f}s")

        has_all_audio = not missing_audio
        has_release = expected_release in actual_names
        if has_all_audio and has_release:
            complete_count += 1
            approved_reviews = [
                record
                for record in review_by_id.get(instrument_id, [])
                if record.get("decision") in set(manifest.get("strict_mode_review_decisions_allowed", []))
            ]
            if not approved_reviews:
                message = f"{instrument_id}: complete delivery still needs professional review decision approved_for_import"
                if args.strict and manifest.get("strict_mode_requires_professional_review") is True:
                    failures.append(message)
                else:
                    warnings.append(message)

    print(
        "Recording inbox: "
        + f"{delivered_count} delivered folder(s), {complete_count} complete folder(s), "
        + f"{len(review_by_id)} reviewed instrument(s)."
    )

    for warning in warnings:
        print(f"WARNING: {warning}")

    if failures:
        print("\nRecording inbox check failed:")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print("Recording inbox check passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
